<?php

namespace RemotePad\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RemoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository {

    /*
    * count remotes
    */ 
    public function countRemotes($userId) {
        /*
         * TO DO!
         *  Find a way to use SELECT SQL_CALC_FOUND_ROWS
         */
        $query = $this->createQueryBuilder('u')
                ->select('COUNT(u.remotes)')
                ->where('u.id = :userId')
                ->setParameter('userId', $userId)
                ->getQuery();
        
        return $query->getSingleScalarResult();
    }

}